name: 'Push To Kyso'
on: [push]
jobs:
  push-to-kyso:
    runs-on: ubuntu-latest
    name: Job to push a report to kyso
    steps:
      - name: Clone repo step
        uses: actions/checkout@v3
      - name: Kyso push step
        id: kyso-push
        uses: sto/kyso-push-action@v1.0.2
        with:
          username: ${{ secrets.KYSO_USER_NAME }}
          token: ${{ secrets.KYSO_USER_TOKEN }}
