name: 'Push To Kyso'
on: [push]
jobs:
  push-to-kyso:
    runs-on: ubuntu-latest
    name: Job to push report to kyso
    steps:
      - name: Clone repo step
        uses: actions/checkout@v3
      - name: Kyso push step
        id: kyso-push
        uses: sto/kyso-push-action@v1
        with:
          install-url: 'https://kyso.io'
          user-name: ${{ secrets.KYSO_USER_NAME }}
          user-token: ${{ secrets.KYSO_USER_TOKEN }}
