name: 'Push To Kyso'
on: [push]
jobs:
  push-to-kyso:
    runs-on: ubuntu-latest
    name: Job to push report to kyso
    env:
      KYSO_INSTALL_URL: 'https://kyso.io'
      KYSO_USER_NAME: ${{ secrets.KYSO_USER_NAME }}
      KYSO_USER_TOKEN: ${{ secrets.KYSO_USER_TOKEN }}
    steps:
      - name: Kyso push step
        id: kyso-push
        uses: sto/kyso-push-action@v1
        with:
          install-url: env.KYSO_INSTALL_URL
          user-name: env.KYSO_USER_NAME
          user-token: env.KYSO_USER_TOKEN
